In [1]:
import numpy as np 
import pandas as pd 

In [2]:
X  = np.array([1.0,2.0,3.0])
X

array([1., 2., 3.])

In [7]:
X = np.random.default_rng().random(size = 5)
X

array([0.88075423, 0.42317108, 0.2364024 , 0.4556828 , 0.70483387])

In [9]:
y = np.random.default_rng().integers(low = 0, high = 2, size = (5,))
y

array([1, 1, 0, 0, 1])

In [10]:
X.shape, y.shape

((5,), (5,))

In [16]:
# just fit these into a polynomial model
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression

# Again set the data
x1 = np.random.default_rng(seed=42).random(size = (150,))
x2 = np.random.default_rng(seed=84).random(size = (150,))
y = np.random.default_rng(seed=142).random(size = (150,))

In [17]:
x1.ndim

1

In [32]:
x1 = x1.reshape(-1,1)
x2 = x1.reshape(-1,1)
X = np.concat((x1,x2), axis = 1)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=42)


In [35]:
# preprocessing the data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

In [53]:
# loading the model
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.pipeline import Pipeline

# set the pipeline for the polynomial regression 2
pipeline = Pipeline([
    ('p', PolynomialFeatures(degree = 2, include_bias = True)),
    ('m', Ridge(alpha = 0.1))
])

# pass the model to the train dataset
pipeline.fit(X_train_scaled, y_train) # model learning

X_test_scaled = scaler.transform(X_test)
# get the prediction on the test dataset
y_pred = pipeline.predict(X_test_scaled)

# get the prediction on the metrics
from sklearn.metrics import mean_absolute_error, r2_score, mean_squared_error
r2_value = r2_score(y_test, y_pred)
print(f"R2 Score: {r2_value}")
mse = mean_squared_error(y_test, y_pred)
print(f"Mean squared error: {mse}")




R2 Score: 0.0060298884545173514
Mean squared error: 0.07381440798319559


In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV, cross_val_predict, LeaveOneOut
Model = {
    'LinearRegression': lambda: Pipeline([('scaler', (StandardScaler())),('pply_features', PolynomialFeatures(degree = 2)),('ridge', Ridge(alpha = 0.6))]),
    'RandomForestRegressor': lambda: GridSearchCV(estimator = RandomForestRegressor(random_state = 42), param_grid={'n_estimators':[50,100,200,300], 'max_depth':[3,5,7,9], 'min_samples_split': [None,2,3,4]}, cv = LeaveOneOut(),scoring = 'r2_score')

}

def train_score(model_name, X_train, y_train):
    # load the model
    model = Model[model_name]()

    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    y_pred_train = model.predict(X_train_scaled)
    r2_value = r2_score(y_train, y_pred_train)
    return r2_value






In [ ]:
class Pinn

array([0.88075423, 0.42317108, 0.2364024 , 0.4556828 , 0.70483387])

In [24]:
x1.shape,x2.shape

((150,), (150,))

In [30]:
x1 = x1.reshape(-1,1)
x2 = x2.reshape(-1,1)
x1.shape, x2.shape

((150, 1), (150, 1))

In [29]:
X.shape

(300, 1)